### ISSUE TITLE
Fails to move mods from folder when attempting to launch Vanilla; instead launches with Rage.

### ISSUE THREAD

**Issue by tylerjkline** [fr-Pursuit/GTAVModdingLauncher#46] opened 2021-10-10 00:35 UTC
I am able to reproduce the bug, and reproduced the bug in this video.

I'm going to try compiling your project and see if the build works.

[Youtube video of bug](https://www.youtube.com/watch?v=X2hYwInSNx4)

**Comment by fr-Pursuit** [comment] 2021-10-10 08:16
That's an interesting bug. What's happening is the launcher apparently giving up while trying to move your mods. Therefore, a failsafe is triggered when you try to launch your vanilla profile while mods are present in your game's directory: that's the first popup.

You then chose to create a new profile with the remaining mods, so the launcher creates it and consider it active. Because the newly created profile contains RPH, it then proceeds to launch it instead of GTA5.exe.

So the main issue here is the launcher not being able to move your mods. I'll try to reproduce the issue on my end.

Appart from LSPDfr, have you installed any other mods?

**Comment by fr-Pursuit** [comment] 2021-10-10 21:52
np ! Having the launcher's logs could prove to be helpful. They're located in a "Latest.log" file next to the launcher's exe.

If the file is missing, enable logging in the launcher's settings

**Comment by fr-Pursuit** [comment] 2022-09-26 12:45
There has not been any activity on this issue for a year, so I'm closing it.
If you have any more questions, feel free to open another issue.

**Closed by fr-Pursuit** 2022-09-26 12:45 UTC
